mkdir "Charts"
mkdir "Data"
mkdir "Investigations"
mkdir "Models"
mkdir "Output"
mkdir "Presentations"
mkdir "Raw"
mkdir "Temp"

mkdir "Data\Macro"
mkdir "Data\Offline Joint"
mkdir "Data\Other"
mkdir "Models\old"
mkdir "Output\DC"
mkdir "Output\Optimisation"
mkdir "Presentations\Old"
mkdir "Raw\Addynamix"
mkdir "Raw\Client"
mkdir "Raw\Media Agency"
mkdir "Raw\Client\Booklets"
mkdir "Raw\Client\Brand Metrics"
mkdir "Raw\Client\Calls-Quotes-Sales"
mkdir "Raw\Client\Competitor"
mkdir "Raw\Client\Directories"
mkdir "Raw\Client\DM"
mkdir "Raw\Client\Events"
mkdir "Raw\Client\Media Plans"
mkdir "Raw\Client\Price"
mkdir "Raw\Client\Tracked Calls"
mkdir "Raw\Client\KPI"
mkdir "Raw\Media Agency\Conversions"
mkdir "Raw\Media Agency\Door Drops"
mkdir "Raw\Media Agency\Online"
mkdir "Raw\Media Agency\Press"
mkdir "Raw\Media Agency\Radio"
mkdir "Raw\Media Agency\Referrals"
mkdir "Raw\Media Agency\Response Tap"
mkdir "Raw\Media Agency\Online\Affiliates"
mkdir "Raw\Media Agency\Online\Display"
mkdir "Raw\Media Agency\Online\GoogleTrends"
mkdir "Raw\Media Agency\Online\PPC"
mkdir "Raw\Media Agency\Online\SEO"
mkdir "Temp\Amy"
mkdir "Temp\Jamal"
